--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-30-2022   
--------------------------------------------------------
DROP SEQUENCE "TEAMFOS"."ORDER_NUM_SEQ";
DROP SEQUENCE "TEAMFOS"."ORDER_NUM_SEQ";
DROP TABLE "TEAMFOS"."DEPARTMENT" cascade constraints;
DROP TABLE "TEAMFOS"."EMPLOYEE" cascade constraints;
DROP TABLE "TEAMFOS"."INSPECTION" cascade constraints;
DROP TABLE "TEAMFOS"."INSPECTION_RESULT" cascade constraints;
DROP TABLE "TEAMFOS"."PURCHASE_ORDER" cascade constraints;
DROP TABLE "TEAMFOS"."DEPARTMENT" cascade constraints;
DROP TABLE "TEAMFOS"."PURCHASE_ORDER" cascade constraints;
DROP TABLE "TEAMFOS"."INSPECTION" cascade constraints;
DROP TABLE "TEAMFOS"."EMPLOYEE" cascade constraints;
DROP TABLE "TEAMFOS"."INSPECTION_RESULT" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence ORDER_NUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEAMFOS"."ORDER_NUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDER_NUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEAMFOS"."ORDER_NUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."DEPARTMENT" 
   (	"DEPT_NUM" NUMBER(2,0), 
	"DEPT_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."EMPLOYEE" 
   (	"EMPL_NUM" NUMBER(6,0), 
	"DEPT_NUM" NUMBER(2,0), 
	"EMPL_NAME" VARCHAR2(50 BYTE), 
	"EMPL_EMAIL" VARCHAR2(50 BYTE), 
	"EMPL_PASSWORD" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table INSPECTION
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."INSPECTION" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"INSPECTION_NUM" NUMBER(2,0), 
	"INSPECTION_DATE" DATE, 
	"INSPECTION_QUANTITY" NUMBER(8,0), 
	"SAMPLE_QUANTITY" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table INSPECTION_RESULT
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."INSPECTION_RESULT" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"INSPECTION_NUM" NUMBER(2,0), 
	"INSPECTION_DEFECT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."PURCHASE_ORDER" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"ORDER_DATE" DATE, 
	"ORDER_QUANTITY" NUMBER(8,0), 
	"EMPL_NUM" NUMBER(6,0), 
	"SUPPORT_NUM" NUMBER(8,0), 
	"CONTRACT_NUM" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."DEPARTMENT" 
   (	"DEPT_NUM" NUMBER(2,0), 
	"DEPT_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table PURCHASE_ORDER
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."PURCHASE_ORDER" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"ORDER_DATE" DATE, 
	"ORDER_QUANTITY" NUMBER(8,0), 
	"EMPL_NUM" NUMBER(6,0), 
	"SUPPORT_NUM" NUMBER(8,0), 
	"CONTRACT_NUM" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table INSPECTION
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."INSPECTION" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"INSPECTION_NUM" NUMBER(2,0), 
	"INSPECTION_DATE" DATE, 
	"INSPECTION_QUANTITY" NUMBER(8,0), 
	"SAMPLE_QUANTITY" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."EMPLOYEE" 
   (	"EMPL_NUM" NUMBER(6,0), 
	"DEPT_NUM" NUMBER(2,0), 
	"EMPL_NAME" VARCHAR2(50 BYTE), 
	"EMPL_EMAIL" VARCHAR2(50 BYTE), 
	"EMPL_PASSWORD" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Table INSPECTION_RESULT
--------------------------------------------------------

  CREATE TABLE "TEAMFOS"."INSPECTION_RESULT" 
   (	"ORDER_NUM" NUMBER(8,0), 
	"INSPECTION_NUM" NUMBER(2,0), 
	"INSPECTION_DEFECT" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."DEPARTMENT_PK" ON "TEAMFOS"."DEPARTMENT" ("DEPT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."EMPLOYEE_PK" ON "TEAMFOS"."EMPLOYEE" ("EMPL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index INSPECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."INSPECTION_PK" ON "TEAMFOS"."INSPECTION" ("ORDER_NUM", "INSPECTION_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index INSPECTION_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."INSPECTION_RESULT_PK" ON "TEAMFOS"."INSPECTION_RESULT" ("ORDER_NUM", "INSPECTION_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."PURCHASE_ORDER_PK" ON "TEAMFOS"."PURCHASE_ORDER" ("ORDER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."DEPARTMENT_PK" ON "TEAMFOS"."DEPARTMENT" ("DEPT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."EMPLOYEE_PK" ON "TEAMFOS"."EMPLOYEE" ("EMPL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index INSPECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."INSPECTION_PK" ON "TEAMFOS"."INSPECTION" ("ORDER_NUM", "INSPECTION_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index INSPECTION_RESULT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."INSPECTION_RESULT_PK" ON "TEAMFOS"."INSPECTION_RESULT" ("ORDER_NUM", "INSPECTION_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Index PURCHASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMFOS"."PURCHASE_ORDER_PK" ON "TEAMFOS"."PURCHASE_ORDER" ("ORDER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER" ;
--------------------------------------------------------
--  DDL for Trigger PURCHASE_ORDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEAMFOS"."PURCHASE_ORDER_TRG" 
BEFORE INSERT ON PURCHASE_ORDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDER_NUM IS NULL THEN
      SELECT ORDER_NUM_SEQ.NEXTVAL INTO :NEW.ORDER_NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEAMFOS"."PURCHASE_ORDER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PURCHASE_ORDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEAMFOS"."PURCHASE_ORDER_TRG" 
BEFORE INSERT ON PURCHASE_ORDER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDER_NUM IS NULL THEN
      SELECT ORDER_NUM_SEQ.NEXTVAL INTO :NEW.ORDER_NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEAMFOS"."PURCHASE_ORDER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DEPT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER"  ENABLE;
  ALTER TABLE "TEAMFOS"."DEPARTMENT" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."DEPARTMENT" MODIFY ("DEPT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER"  ENABLE;
  ALTER TABLE "TEAMFOS"."EMPLOYEE" MODIFY ("EMPL_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."EMPLOYEE" MODIFY ("EMPL_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."EMPLOYEE" MODIFY ("EMPL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."EMPLOYEE" MODIFY ("DEPT_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."EMPLOYEE" MODIFY ("EMPL_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSPECTION
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."INSPECTION" ADD CONSTRAINT "INSPECTION_PK" PRIMARY KEY ("ORDER_NUM", "INSPECTION_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER"  ENABLE;
  ALTER TABLE "TEAMFOS"."INSPECTION" MODIFY ("SAMPLE_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION" MODIFY ("INSPECTION_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION" MODIFY ("INSPECTION_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION" MODIFY ("INSPECTION_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSPECTION_RESULT
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."INSPECTION_RESULT" ADD CONSTRAINT "INSPECTION_RESULT_PK" PRIMARY KEY ("ORDER_NUM", "INSPECTION_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER"  ENABLE;
  ALTER TABLE "TEAMFOS"."INSPECTION_RESULT" MODIFY ("INSPECTION_DEFECT" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION_RESULT" MODIFY ("INSPECTION_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."INSPECTION_RESULT" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_PK" PRIMARY KEY ("ORDER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PURCHASEORDER"  ENABLE;
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("CONTRACT_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("SUPPORT_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("EMPL_NUM" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("ORDER_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("DEPT_NUM")
	  REFERENCES "TEAMFOS"."DEPARTMENT" ("DEPT_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSPECTION
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."INSPECTION" ADD CONSTRAINT "INSPECTION_FK1" FOREIGN KEY ("ORDER_NUM")
	  REFERENCES "TEAMFOS"."PURCHASE_ORDER" ("ORDER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSPECTION_RESULT
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."INSPECTION_RESULT" ADD CONSTRAINT "INSPECTION_RESULT_FK1" FOREIGN KEY ("ORDER_NUM", "INSPECTION_NUM")
	  REFERENCES "TEAMFOS"."INSPECTION" ("ORDER_NUM", "INSPECTION_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE_ORDER
--------------------------------------------------------

  ALTER TABLE "TEAMFOS"."PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_FK1" FOREIGN KEY ("EMPL_NUM")
	  REFERENCES "TEAMFOS"."EMPLOYEE" ("EMPL_NUM") ENABLE;
