--------------------------------------------------------
--  파일이 생성됨 - 토요일-8월-12-2023
--------------------------------------------------------
REM INSERTING into C##PURCHASE.DEPARTMENT
SET DEFINE OFF;
Insert into C##PURCHASE.DEPARTMENT (DEPT_NUM,DEPT_NAME) values (1,'테스트');
REM INSERTING into C##PURCHASE.EMPLOYEE
SET DEFINE OFF;
Insert into C##PURCHASE.EMPLOYEE (EMPL_NUM,DEPT_NUM,EMPL_NAME,EMPL_EMAIL,EMPL_PASSWORD,AUTHORITY) values (1,1,'홍길동','holopart@gmail.com','$2a$10$7tlUP3NjmVS9JEmrbVy/hOoDO8OB7q6rlUWPC0.0ZdwyNkSIHTm8O','ROLE_PD');
REM INSERTING into C##PURCHASE.INSPECTION
SET DEFINE OFF;
REM INSERTING into C##PURCHASE.INSPECTION_RESULT
SET DEFINE OFF;
REM INSERTING into C##PURCHASE.PURCHASE_ORDER
SET DEFINE OFF;
REM INSERTING into C##PURCHASE.TBL_COMPANY
SET DEFINE OFF;
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('1','ABC Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('2','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('3','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('4','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('5','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('6','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('7','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('8','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('9','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
Insert into C##PURCHASE.TBL_COMPANY (CODE,NAME,BUSINESS_NUMBER,TAXCODE,OWNER,CONTACT,ADDRESS,ACCOUNT,COMPANY_SIZE,CATEGORY,SALES,DEAL_TYPE,DOMESTIC_FOREIGN,CURRENCY,START_DATE,END_DATE,INVOICE_ISSUE,COMEMPLOYEE,COMEMAIL) values ('10','ABCD Corporation','1234567890','TAX123','John Doe','123-456-7890','123 Main St, City','123456789','Medium','Technology',1000000,'New Deal','Domestic','USD',to_date('23/08/01','RR/MM/DD'),'2023-12-31','Monthly','50','john.doe@example.com');
REM INSERTING into C##PURCHASE.TBL_CONTRACT
SET DEFINE OFF;
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (1,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (2,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (3,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (4,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (5,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (6,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (7,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (8,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (9,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (10,5,'Immediate',10000,'1','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (11,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (12,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (13,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (14,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (15,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (16,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (17,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (18,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (19,5,'Immediate',10000,'2','1');
Insert into C##PURCHASE.TBL_CONTRACT (CONTRACTNO,PARTSSUPPLY,TRANSFERCONDITIONS,UNITPRICE,PARTCODE,CODE) values (20,5,'Immediate',10000,'2','1');
REM INSERTING into C##PURCHASE.TBL_PART
SET DEFINE OFF;
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (1,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (2,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (3,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (4,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (5,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (6,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (7,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (8,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (9,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
Insert into C##PURCHASE.TBL_PART (PARTCODE,PARTNAME,NICKNAME,LIBRARY,REMARK,COMMON,DRW_NO,DRW_IMG) values (10,'Widget A','Nick A','Lib1','Standard widget','Common1','D001','drawing001.jpg');
REM INSERTING into C##PURCHASE.TBL_SUPPORT
SET DEFINE OFF;
Insert into C##PURCHASE.TBL_SUPPORT (SUPPORTNO,PARTCODE,REQUIREMENT,MATERIALPROCESS,DAYSCHEDULE,DELIVERYDATE) values (1,'1','100','Machining and welding',5,to_date('23/08/15','RR/MM/DD'));
Insert into C##PURCHASE.TBL_SUPPORT (SUPPORTNO,PARTCODE,REQUIREMENT,MATERIALPROCESS,DAYSCHEDULE,DELIVERYDATE) values (2,'2','100','Machining',5,to_date('24/09/19','RR/MM/DD'));
Insert into C##PURCHASE.TBL_SUPPORT (SUPPORTNO,PARTCODE,REQUIREMENT,MATERIALPROCESS,DAYSCHEDULE,DELIVERYDATE) values (3,'3','100','Machining',5,to_date('23/09/19','RR/MM/DD'));
Insert into C##PURCHASE.TBL_SUPPORT (SUPPORTNO,PARTCODE,REQUIREMENT,MATERIALPROCESS,DAYSCHEDULE,DELIVERYDATE) values (4,'4','100','Machining',5,to_date('22/09/19','RR/MM/DD'));
REM INSERTING into C##PURCHASE.WAREHOUSING
SET DEFINE OFF;
